### ISSUE TITLE
When to release your code and re-rendering data

### ISSUE THREAD

**Issue by Schizophreni** [zkawfanx/RLP#1]
Congratulations for your awesome work accepted by ICCV 2023. I am very interested in your nighttime rain removal work, so when will you release your re-rendering GTA-nighttime dataset as well as the source codes ?

**Comment by zkawfanx** [comment]
Thank you for your interest in our work. I am working hard to clean up the code and prepare & upload the re-rendered data to cloud disk, they will be hopefuly finished in about 1~2 weeks. Stay tuned.

**Comment by Schizophreni** [comment]
Thanks for your reply and sharing

**Comment by jiaqixuac** [comment]
Thanks for your nice work.
Is there any update about the release?

**Comment by zkawfanx** [comment]
> Thanks for your nice work. Is there any update about the release?

Thanks for your interest in our work.

Embarrassingly, I have to apologize for the delay of the code&data release because I am still struggling with the new work for CVPR2024 right now. Wish I can get a breath to get these things done.

**Comment by zkawfanx** [comment]
@Schizophreni @jiaqixuac 

Hi, the initial data has been released and the code is still under cleaning, coming soooooooon.

**Comment by zkawfanx** [comment]
The code is released.
