### ISSUE TITLE
Visualization of RLP

### ISSUE THREAD

**Issue by hhhhhhalf** [zkawfanx/RLP#10]
Hello, thank you very much for your excellent work.I would like to ask how you did the visualization work for RLP in your paper?Can you release the relevant code?Thank you

**Comment by zkawfanx** [comment]
Hi, the intermediate RLP output is a single-channel map and you can directly visualize it into colored map using the cmap function of matplotlib library.

**Comment by hhhhhhalf** [comment]
Ok, thank you for your reply
