### ISSUE TITLE
训练流程咨询

### ISSUE THREAD

**Issue by Feecuin** [zkawfanx/RLP#3]
你好，我试着训练你的代码，发现按照readme来loss一直是四十多降不下来，是我训练方法有问题吗？

**Comment by zkawfanx** [comment]
你好，我在清理代码时不小心移除了部分loss更新语句带来的bug，已经修复，你可以同步一下再试试loss是否下降

**Comment by Feecuin** [comment]
你好，我看了下你最新更新是三个月前，这个代码我是上礼拜才拉到本地跑的，发现loss降不下来，第一轮和第十轮的loss几乎是一样的

**Comment by zkawfanx** [comment]
我刚才看到issue后更新了train.py，请再更新一下本地的版本

**Comment by Feecuin** [comment]
好的哥，我再试试

**Comment by Feecuin** [comment]
ok了哥，loss降了，不过每个poech的训练时间翻倍了，后续有啥问题我再来请教你，最近想试试这方面还在摸索中

**Comment by zkawfanx** [comment]
你可能需要从timm库import loss_scaler，时间增长是正常的，因为前面bug导致梯度没更新

**Comment by Feecuin** [comment]
老哥，你这篇等于是提出了一个先验吗？那个RPIM充当一个注意力块么？ 我没有从timm库import，我更新train.py到本地后bash train.sh能运行我就没动他了

**Comment by zkawfanx** [comment]
你这样理解没什么问题。你再加上from timm.utils import NativeScaler速度可能就提上去了

**Comment by Feecuin** [comment]
老哥，我有点不太懂，为啥从timm库导入这个NativeScaler会更快，我看了下cuda好像也自带了这个NativeScaler，是什么原理吗？我刚研一所以有些地方挺懵的，我百度了一下没看到有解释这个的

**Comment by zkawfanx** [comment]
你可以尝试一下，我没有实际测试过，也可能速度差不多

**Comment by Feecuin** [comment]
好的哥，导入timm的和cuda自带的都一样的吧？

**Comment by zkawfanx** [comment]
嗯
