### ISSUE TITLE
请求获取对比实验中其他模型的训练权重

### ISSUE THREAD

**Issue by Nnnnnnnight** [zkawfanx/RLP#4]
您好！最近在复现代码的过程中，使用MPRNet训练您文章中提出的数据集，发现PSNR跟您提到的有些差距。如果可以的话可以分享一下对比实验其他模型的权重文件吗？谢谢！

**Comment by zkawfanx** [comment]
你好，可以请你先提供你详细的实验setting以及遇到的具体问题吗？我最近可能没有时间整理，后续我可以抽空整理一下，你也可以留个邮箱。

**Comment by Nnnnnnnight** [comment]
感谢您的回复！我使用MPRNet默认的实验参数进行训练，测试的PSNR指标很高。我估计可能是数据集设置相关的问题，所以想获取论文中的权重尝试一下。我的邮箱是handz@shu.edu.cn，再次感谢！

**Comment by Nnnnnnnight** [comment]
您好！我已经查出原因了，打扰了！期待您后续整理的权重文件。谢谢！

**Comment by Nnnnnnnight** [comment]
However, after checking carefully, we find that there exist a few scenes with misalignments due to operation mistakes during collection. We filter out these scenes and there's about 0.5dB improvement in PSNR, which applys to all evaluated methods.

**Comment by Nnnnnnnight** [comment]
However, after checking carefully, we find that there exist a few scenes with misalignments due to operation mistakes during collection. We filter out these scenes and there's about 0.5dB improvement in PSNR, which applys to all evaluated methods.
请问下载链接的数据集包含这些错误场景吗？还有就是0.5db提升是指论文中表1的所有方法吗？

**Comment by zkawfanx** [comment]
> 您好！我已经查出原因了，打扰了！期待您后续整理的权重文件。谢谢！

已通过邮件发给你了，注意查收
