### ISSUE TITLE
对比方法咨询

### ISSUE THREAD

**Issue by Feecuin** [zkawfanx/RLP#5]
老哥，我又来了，我想问下你的对比方法都是重新训的吗？是在你提供的kaggle上面的数据集上么？方便分享一下权重文件吗老哥，谢谢

**Comment by zkawfanx** [comment]
是的，最近不一定有空整理，有机会的话再看看吧

**Comment by Feecuin** [comment]
好的哥，感谢感谢，我也想拿来跑对比方法，卡不够用没什么时间训了

**Comment by Feecuin** [comment]
哥，权重文件不用了，我自己得重新训，因为数据集我从5000张减到2000张，但是有几个对比方法代码有点问题，例如MPRNet的损失也是一直下不去，PSNR越来越低，去原github上看那些方法也没解决,老哥知道问题出在哪吗？或者老哥方便分享下当时对比方法调好的代码吗？
![image](https://github.com/zkawfanx/RLP/assets/46098294/3874465f-68fc-4e7f-9ba9-50d7f4c7f610)

**Comment by Feecuin** [comment]
![image](https://github.com/zkawfanx/RLP/assets/46098294/0a63a161-7945-4c80-83d7-4716316b006b)

**Comment by Feecuin** [comment]
老哥，你这rainy和gt是10:1的，gt只有500张，我把gt复制十倍变成5000张效果是一样的吗？有些方法得input和gt数量一比一我直接把gt复制十倍拿来一起训，然后和RLP一起测指标对比可以不？

**Comment by zkawfanx** [comment]
> 哥，权重文件不用了，我自己得重新训，因为数据集我从5000张减到2000张，但是有几个对比方法代码有点问题，例如MPRNet的损失也是一直下不去，PSNR越来越低，去原github上看那些方法也没解决,老哥知道问题出在哪吗？或者老哥方便分享下当时对比方法调好的代码吗？ ![image](https://private-user-images.githubusercontent.com/46098294/318280074-3874465f-68fc-4e7f-9ba9-50d7f4c7f610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTIzOTEsIm5iZiI6MTcxMTk1MjA5MSwicGF0aCI6Ii80NjA5ODI5NC8zMTgyODAwNzQtMzg3NDQ2NWYtNjhmYy00ZTdmLTliYTktNTBkN2Y0YzdmNjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0M2Y5OGMzMDU1ZWZlNDZmZTUwM2JkYTU0YzBhZDE1M2Y5YjYxMGVhMzNjZDFmYzg5MDYxYzQxMjA1YWZhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iP1xkSDsDWcpG3hw8ENdUGtLVoChIL7stoSh33QEySs)

MPRNet代码训练没啥问题，我没有改动

**Comment by zkawfanx** [comment]
> 老哥，你这rainy和gt是10:1的，gt只有500张，我把gt复制十倍变成5000张效果是一样的吗？有些方法得input和gt数量一比一我直接把gt复制十倍拿来一起训，然后和RLP一起测指标对比可以不？

rainy中下标'xxxx_00'到'xxxx_09'都是对应编号’0000‘的gt，没有重复保存只是节省空间，训练时你读取文件时对应上即可

**Comment by Feecuin** [comment]
> > 老哥，你这rainy和gt是10:1的，gt只有500张，我把gt复制十倍变成5000张效果是一样的吗？有些方法得input和gt数量一比一我直接把gt复制十倍拿来一起训，然后和RLP一起测指标对比可以不？
> 
> rainy中下标'xxxx_00'到'xxxx_09'都是对应编号’0000‘的gt，没有重复保存只是节省空间，训练时你读取文件时对应上即可

好的哥，那就行
