### ISSUE TITLE
cuda out of memory error

### ISSUE THREAD

**Issue by shubhamharsh** [zkawfanx/RLP#6]
I am getting cuda out of memory error, while testing UNet_RLP_RPIM model you have given, when ruuning in collab. Can you suggest some methods to overcome it ? Also, what file directory we have to give to test the images(gt or rainy)?

**Comment by zkawfanx** [comment]
Hi, could you provide more details about your testing setting in colab? Normally, it will occupy less than 12GB VRAM for UNet_RLP_RPIM to inference on 1080p images with batch_size = 1. You may reduce inference batch size to 1 to see if it works.

BTW, I am not sure what you mean by last, if I am right, the file directory you give is the root folder that contains both gt and rainy.
