### ISSUE TITLE
实验数据相关

### ISSUE THREAD

**Issue by Nnnnnnnight** [zkawfanx/RLP#7]
However, after checking carefully, we find that there exist a few scenes with misalignments due to operation mistakes during collection. We filter out these scenes and there's about 0.5dB improvement in PSNR, which applys to all evaluated methods.
请问下载链接的数据集包含这些错误场景吗？还有就是0.5db提升是指论文中表1的所有方法吗？

**Comment by zkawfanx** [comment]
下载链接提供的是原始数据，错误场景也保留在内。0.5db提升是指所有方法。

**Comment by Nnnnnnnight** [comment]
好的知道了，谢谢！另外请问有整理预训练权重的计划吗？

**Comment by zkawfanx** [comment]
> 好的知道了，谢谢！另外请问有整理预训练权重的计划吗？

已通过邮件发给你了，注意查收

**Comment by Nnnnnnnight** [comment]
您好！我检查这个邮箱handz@shu.edu.cn并没有发现收到邮件，您也可以发这个邮箱1094190725@qq.com。谢谢！

**Comment by zkawfanx** [comment]
> 您好！我检查这个邮箱[handz@shu.edu.cn](mailto:handz@shu.edu.cn)并没有发现收到邮件，您也可以发这个邮箱[1094190725@qq.com](mailto:1094190725@qq.com)。谢谢！

看看有没有被拦截或者垃圾箱吧

**Comment by Nnnnnnnight** [comment]
我检查了邮件的垃圾箱也没有，但是这几天我们的校园网确实很差。麻烦您能通过1094190725@qq.com再发送一份吗？麻烦您了，谢谢！
![111137](https://github.com/zkawfanx/RLP/assets/162005851/f59da2a1-f522-466c-86ba-496be52ac475)

**Comment by zkawfanx** [comment]
> 我检查了邮件的垃圾箱也没有，但是这几天我们的校园网确实很差。麻烦您能通过[1094190725@qq.com](mailto:1094190725@qq.com)再发送一份吗？麻烦您了，谢谢！ ![111137](https://private-user-images.githubusercontent.com/162005851/320280769-f59da2a1-f522-466c-86ba-496be52ac475.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTMyMDIsIm5iZiI6MTcxMjQ5MjkwMiwicGF0aCI6Ii8xNjIwMDU4NTEvMzIwMjgwNzY5LWY1OWRhMmExLWY1MjItNDY2Yy04NmJhLTQ5NmJlNTJhYzQ3NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxMjI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTI1YmUzOTI0YmI5YjMxZDI4MjM0MWUzNGI0NWRmZGY1MjhjZjlmOGIwMmU0ODgwNmZiYjgzZDUwNjUwMzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZyzSsi9uAY5_JZk9EJdWSaMSr_fuPUeKhu6W-m5iSiQ)

注意查收

**Comment by Nnnnnnnight** [comment]
谢谢！已经收到了！请问后续会放出其他方法的权重文件吗？

**Comment by zkawfanx** [comment]
> 谢谢！已经收到了！请问后续会放出其他方法的权重文件吗？

我们并没有此计划，有其他问题随时交流

**Comment by Nnnnnnnight** [comment]
> > 谢谢！已经收到了！请问后续会放出其他方法的权重文件吗？
> 
> 我们并没有此计划，有其他问题随时交流

好的好的
