### ISSUE TITLE
Derainig module咨询

### ISSUE THREAD

**Issue by Feecuin** [zkawfanx/RLP#9]
老哥，你这deraining module里的UNet和Uformer都是源论文一样的代码么，如果把你提出的两个块不加单独训的话是不是可以得到UNet和Uformer的数据，你对比方法贴的UNet和Uformer的数据是不是这样训的呀？我搞了个1k的数据集训你的方法，70秒出一轮，训Uformer40秒，UNet14秒...是不是哪里有问题，还是说就是这么快？

**Comment by zkawfanx** [comment]
是的，不加RLP和RPIM两个模块的话，DM本身就是UNet和Uformer，直接训练即可。RLP需要迭代多次，所以训练起来会更慢，DM单独训会更快

**Comment by Feecuin** [comment]
老哥方便加个微信聊吗？我现在训的数据集发现咱这方法跑不过PReNet，有些细节想和你确认下我训没训错

**Comment by Feecuin** [comment]
如果老哥方便的话，我的微信号是ideaalne1

**Comment by zkawfanx** [comment]
1k张图数量其实有点少了，可能并不能充分训练，尤其是Uformer做主干的时候。PReNet本身结构简单，性能也还行，训练数据量小的情况下可能反而会有优势
